/*
Deployment script for db_Zon_Huw_Live

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "db_Zon_Huw_Live"
:setvar DefaultFilePrefix "db_Zon_Huw_Live"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
Table [dbo].[sqlmapoutput] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[sqlmapoutput])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping Table [dbo].[sqlmapoutput]...';


GO
DROP TABLE [dbo].[sqlmapoutput];


GO
PRINT N'Creating User-Defined Table Type [dbo].[PrescriptionImageList]...';


GO
CREATE TYPE [dbo].[PrescriptionImageList] AS TABLE (
    [ImageUrl] NVARCHAR (500) NULL);


GO
PRINT N'Altering Table [dbo].[CheckOutUserProductTransactions]...';


GO
ALTER TABLE [dbo].[CheckOutUserProductTransactions]
    ADD [ExpectedDeliveryDate] DATETIME NULL;


GO
PRINT N'Altering Table [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products]
    ADD [CdnProductImgUrl]  NVARCHAR (500) NULL,
        [CdnProductImgUrl2] NVARCHAR (500) NULL;


GO
PRINT N'Altering Table [dbo].[UserProductTransactions]...';


GO
ALTER TABLE [dbo].[UserProductTransactions]
    ADD [ExpectedDeliveryDate] DATETIME        NULL,
        [GST_Percentage]       DECIMAL (5, 2)  NULL,
        [GST_Amount]           DECIMAL (18, 2) NULL,
        [CGST]                 DECIMAL (18, 2) NULL,
        [SGST]                 DECIMAL (18, 2) NULL,
        [IGST]                 DECIMAL (18, 2) NULL,
        [BaseAmount]           DECIMAL (18, 2) NULL,
        [ProductOriginalCost]  DECIMAL (18, 2) NULL;


GO
PRINT N'Creating Table [dbo].[Cart]...';


GO
CREATE TABLE [dbo].[Cart] (
    [CartId]            BIGINT           IDENTITY (1, 1) NOT NULL,
    [UserId]            BIGINT           NULL,
    [GuestId]           UNIQUEIDENTIFIER NULL,
    [Status]            VARCHAR (20)     NOT NULL,
    [CreatedOn]         DATETIME         NOT NULL,
    [UpdatedOn]         DATETIME         NOT NULL,
    [Has_Promo_Code]    BIT              NOT NULL,
    [Promo_Code_ID]     BIGINT           NULL,
    [Promo_Code_Amount] DECIMAL (10, 2)  NULL,
    PRIMARY KEY CLUSTERED ([CartId] ASC)
);


GO
PRINT N'Creating Table [dbo].[CartItem]...';


GO
CREATE TABLE [dbo].[CartItem] (
    [CartItemId]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [CartId]             BIGINT          NOT NULL,
    [ProductId]          BIGINT          NOT NULL,
    [Quantity]           INT             NOT NULL,
    [UnitPrice]          DECIMAL (18, 2) NOT NULL,
    [DiscountPercentage] DECIMAL (5, 2)  NULL,
    [DiscountAmount]     DECIMAL (18, 2) NULL,
    [CreatedOn]          DATETIME        NOT NULL,
    [UpdatedOn]          DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([CartItemId] ASC),
    CONSTRAINT [UQ_Cart_Product] UNIQUE NONCLUSTERED ([CartId] ASC, [ProductId] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserOtp]...';


GO
CREATE TABLE [dbo].[UserOtp] (
    [UserOtpId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [UserId]    BIGINT        NOT NULL,
    [OtpHash]   VARCHAR (256) NOT NULL,
    [ExpiresAt] DATETIME      NOT NULL,
    [Attempts]  INT           NOT NULL,
    [IsUsed]    BIT           NOT NULL,
    [CreatedOn] DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([UserOtpId] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_Cart_HasPromoCode]...';


GO
ALTER TABLE [dbo].[Cart]
    ADD CONSTRAINT [DF_Cart_HasPromoCode] DEFAULT ((0)) FOR [Has_Promo_Code];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Cart]...';


GO
ALTER TABLE [dbo].[Cart]
    ADD DEFAULT ('ACTIVE') FOR [Status];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Cart]...';


GO
ALTER TABLE [dbo].[Cart]
    ADD DEFAULT (getdate()) FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Cart]...';


GO
ALTER TABLE [dbo].[Cart]
    ADD DEFAULT (getdate()) FOR [UpdatedOn];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[CartItem]...';


GO
ALTER TABLE [dbo].[CartItem]
    ADD DEFAULT (getdate()) FOR [UpdatedOn];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[CartItem]...';


GO
ALTER TABLE [dbo].[CartItem]
    ADD DEFAULT (getdate()) FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[UserOtp]...';


GO
ALTER TABLE [dbo].[UserOtp]
    ADD DEFAULT ((0)) FOR [Attempts];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[UserOtp]...';


GO
ALTER TABLE [dbo].[UserOtp]
    ADD DEFAULT (getdate()) FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[UserOtp]...';


GO
ALTER TABLE [dbo].[UserOtp]
    ADD DEFAULT ((0)) FOR [IsUsed];


GO
PRINT N'Creating Default Constraint [dbo].[DF_CurrencyCode]...';


GO
ALTER TABLE [dbo].[CheckOutPaymentTransactions]
    ADD CONSTRAINT [DF_CurrencyCode] DEFAULT ('INR') FOR [CurrencyCode];


GO
PRINT N'Creating Foreign Key [dbo].[FK_Cart_Coupon]...';


GO
ALTER TABLE [dbo].[Cart] WITH NOCHECK
    ADD CONSTRAINT [FK_Cart_Coupon] FOREIGN KEY ([Promo_Code_ID]) REFERENCES [dbo].[Tbl_Coupon_Info] ([Coupon_Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CartItem_Cart]...';


GO
ALTER TABLE [dbo].[CartItem] WITH NOCHECK
    ADD CONSTRAINT [FK_CartItem_Cart] FOREIGN KEY ([CartId]) REFERENCES [dbo].[Cart] ([CartId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserOtp_User]...';


GO
ALTER TABLE [dbo].[UserOtp] WITH NOCHECK
    ADD CONSTRAINT [FK_UserOtp_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] ([UserId]);


GO
PRINT N'Creating Check Constraint [dbo].[CK_Cart_Owner]...';


GO
ALTER TABLE [dbo].[Cart] WITH NOCHECK
    ADD CONSTRAINT [CK_Cart_Owner] CHECK ([UserId] IS NOT NULL OR [GuestId] IS NOT NULL);


GO
PRINT N'Creating Trigger [dbo].[inert_GSTupate]...';


GO
CREATE TRIGGER [dbo].[inert_GSTupate] ON [dbo].[PaymentTransactions]
    AFTER INSERT
	AS
    BEGIN
	declare @payID bigint,@userid int,@gstAmount money=0; 
	--for trigger
	select @payID=i.PaymentTransactionId, @userid=UserId   from inserted i  
	select @payID=PaymentTransactionId, @userid=UserId 
	from  PaymentTransactions 	where PaymentTransactionId=@payID
	select @gstAmount= sum(((up.ProductCost-(up.ProductCost*100/(100+GST)))))  from  UserProductTransactions up 
	join Products p on p.ProductId=up.ProductId  where @payID=up.PaymentTransactionId

	if (select count(*) from UserAddresses where userid=@userid and StateId=36  )<>1   
	  update PaymentTransactions set  igst=@gstAmount,sgst=0,cgst=0 where PaymentTransactionId=@payID
	  else
	  update PaymentTransactions set  igst=0,sgst=round(@gstAmount/2,2),cgst=round(@gstAmount/2 ,2) where PaymentTransactionId=@payID
  
	end
GO
PRINT N'Creating Trigger [dbo].[Update_GSTupate]...';


GO
CREATE TRIGGER [dbo].[Update_GSTupate] ON [dbo].[PaymentTransactions]
    AFTER Update
	AS
    BEGIN
	declare @payID bigint,@userid int,@gstAmount money=0,@OrderCurrentStatus int; 
	--for trigger
	select @payID=i.PaymentTransactionId, @userid=UserId from inserted i  
	select @payID=PaymentTransactionId, @userid=UserId from  PaymentTransactions  where PaymentTransactionId=@payID
	select @gstAmount= sum(((up.ProductCost-(up.ProductCost*100/(100+GST)))))  from  UserProductTransactions up 
	join Products p on p.ProductId=up.ProductId  where @payID=up.PaymentTransactionId
	if @OrderCurrentStatus=6
	if (select count(*) from UserAddresses where userid=@userid and StateId=36  )<>1   
	  update PaymentTransactions set  igst=@gstAmount,sgst=0,cgst=0 where PaymentTransactionId=@payID
	  else
	  update PaymentTransactions set  igst=0,sgst=round(@gstAmount/2,2),cgst=round(@gstAmount/2 ,2) where PaymentTransactionId=@payID
  else  if @OrderCurrentStatus=9
 begin 
INSERT INTO [dbo].[RetunOrders]
               select PaymentTransactionId,getdate(),OrdersReturnReason ,OrdersReturnAction  from PaymentTransactions where PaymentTransactionId =@payID
 end
	end
GO
PRINT N'Creating Trigger [dbo].[insert_coupen]...';


GO
 create TRIGGER [dbo].[insert_coupen] ON [dbo].[Tbl_Coupon_Info]
    AFTER INSERT
    AS
    BEGIN
	 insert into [Healthurwealth].[Tbl_Promo_Codes]   
	 select top 1 [Coupon_Id],[Coupon_Code],[Coupon_Amount],[Valid_From],[Valid_To] ,[Min_Cart_Value],1 
	 from  Tbl_Coupon_Info order by Coupon_Id  desc

    END
GO
PRINT N'Creating Trigger [dbo].[update_coupon]...';


GO
 CREATE TRIGGER update_coupon ON Tbl_Coupon_Info
    AFTER update
    AS
    BEGIN
	
	 update [Healthurwealth].[Tbl_Promo_Codes]   set 
	[Promo_Code_ID]= tc.[Coupon_Id],PromoCode= [Coupon_Code],amount= [Coupon_Amount], 
	[Valid_From]=tc.[Valid_From],[Valid_To]=tc.Valid_To ,Minimum_Order_amount= [Min_Cart_Value],IsActive=1 
	from inserted tc where  tc.Coupon_Id= Promo_Code_ID
    END
GO
PRINT N'Creating Trigger [dbo].[InsertProductName]...';


GO
CREATE TRIGGER [dbo].[InsertProductName] ON [dbo].[UserProductTransactions]
    AFTER INSERT
	AS
    BEGIN
	declare @productID bigint,@payID bigint,@userproductid bigint;
	declare @productName nvarchar(250);
	select @productID=i.ProductId,@userproductid=i.TransactionId  from inserted i  
	--for trigger
	select @productName=productname from Products where ProductId=@productID;
	update UserProductTransactions set ProductName=@productName where TransactionId=@userproductid
	end
GO
PRINT N'Creating Function [dbo].[fn_GetShippingCharge]...';


GO
CREATE FUNCTION [dbo].[fn_GetShippingCharge]
(
    @SubTotal DECIMAL(10,2),
    @PaymentMode VARCHAR(50),
    @TotalWeightGrams INT
)
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @ShippingCharge DECIMAL(10,2);

    --------------------------------------------------
    -- 1️) HARD RULE: Weight override
    --------------------------------------------------
    IF (@TotalWeightGrams >= 500)
    BEGIN
        RETURN 99;
    END

    --------------------------------------------------
    -- 2️) Order value logic (only for ≤500g)
    --------------------------------------------------
    IF (@PaymentMode = 'Cash On Delivery')
    BEGIN
          IF (@SubTotal >= 1000)
            SET @ShippingCharge = 0;
        ELSE
            SET @ShippingCharge = 49;
			
    END
    ELSE -- Prepaid
    BEGIN
		IF (@SubTotal >= 500)
            SET @ShippingCharge = 0;
        ELSE
            SET @ShippingCharge = 49;
    END

    RETURN @ShippingCharge;
END
GO
PRINT N'Creating Function [dbo].[fn_CalculateGST]...';


GO
CREATE FUNCTION dbo.fn_CalculateGST
(
    @Price DECIMAL(18,2),
    @GST DECIMAL(5,2),
    @StateName NVARCHAR(100)
)
RETURNS TABLE
AS
RETURN
(
    SELECT
        --------------------------------------------------
        -- GST Amount (inclusive extraction)
        --------------------------------------------------
        GST_Amount = ROUND((@Price * @GST) / (100 + @GST), 2),

        --------------------------------------------------
        -- CGST
        --------------------------------------------------
        CGST = CASE 
            WHEN LOWER(@StateName) = 'telangana'
            THEN ROUND(((@Price * @GST) / (100 + @GST)) / 2, 2)
            ELSE 0
        END,

        --------------------------------------------------
        -- SGST
        --------------------------------------------------
        SGST = CASE 
            WHEN LOWER(@StateName) = 'telangana'
            THEN ROUND(((@Price * @GST) / (100 + @GST)) / 2, 2)
            ELSE 0
        END,

        --------------------------------------------------
        -- IGST
        --------------------------------------------------
        IGST = CASE 
            WHEN LOWER(@StateName) <> 'telangana'
            THEN ROUND((@Price * @GST) / (100 + @GST), 2)
            ELSE 0
        END,

        --------------------------------------------------
        -- Base Amount
        --------------------------------------------------
        BaseAmount = ROUND(
            @Price - ((@Price * @GST) / (100 + @GST)), 
        2)
);
GO
PRINT N'Creating Procedure [dbo].[SP_Cart_AddOrUpdateItem]...';


GO
CREATE PROCEDURE [dbo].[SP_Cart_AddOrUpdateItem]
(
    @CartId BIGINT,
    @ProductId BIGINT,
    @Quantity INT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @UnitPrice DECIMAL(18,2);

    SELECT @UnitPrice = ProductCost
    FROM Products
    WHERE ProductId = @ProductId
      AND IsActive = 1
      AND IsDeleted = 0;

    IF EXISTS (SELECT 1 FROM CartItem WHERE CartId = @CartId AND ProductId = @ProductId)
    BEGIN
        UPDATE CartItem
        SET Quantity +=  @Quantity,
            UpdatedOn = GETDATE()
        WHERE CartId = @CartId AND ProductId = @ProductId;
    END
    ELSE
    BEGIN
        INSERT INTO CartItem (CartId, ProductId, Quantity, UnitPrice)
        VALUES (@CartId, @ProductId, @Quantity, @UnitPrice);
    END

    UPDATE Cart SET UpdatedOn = GETDATE() WHERE CartId = @CartId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Cart_GetItems]...';


GO
CREATE PROCEDURE SP_Cart_GetItems
(
    @CartId BIGINT
)
AS
BEGIN
    SELECT
        ci.CartItemId,
        ci.ProductId,
        p.ProductName,
        p.ProductImgUrl,
        ci.Quantity,
        ci.UnitPrice,
        (ci.UnitPrice * ci.Quantity) AS TotalPrice
    FROM CartItem ci
    INNER JOIN Products p ON ci.ProductId = p.ProductId
    WHERE ci.CartId = @CartId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Cart_GetOrCreate]...';


GO
CREATE PROCEDURE SP_Cart_GetOrCreate
(
    @UserId BIGINT = NULL,
    @GuestId UNIQUEIDENTIFIER = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @CartId BIGINT;

    SELECT @CartId = CartId
    FROM Cart
    WHERE Status = 'ACTIVE'
      AND (
           (@UserId IS NOT NULL AND UserId = @UserId)
        OR (@GuestId IS NOT NULL AND GuestId = @GuestId)
      );

    IF @CartId IS NULL
    BEGIN
        INSERT INTO Cart (UserId, GuestId)
        VALUES (@UserId, @GuestId);

        SET @CartId = SCOPE_IDENTITY();
    END

    SELECT @CartId AS CartId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Cart_MergeGuestToUser]...';


GO
CREATE PROCEDURE SP_Cart_MergeGuestToUser
(
    @GuestId UNIQUEIDENTIFIER,
    @UserId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @GuestCartId BIGINT;
    DECLARE @UserCartId BIGINT;

    SELECT @GuestCartId = CartId FROM Cart WHERE GuestId = @GuestId AND Status = 'ACTIVE';
    SELECT @UserCartId = CartId FROM Cart WHERE UserId = @UserId AND Status = 'ACTIVE';

    IF @GuestCartId IS NULL RETURN;

    IF @UserCartId IS NULL
    BEGIN
        UPDATE Cart
        SET UserId = @UserId, GuestId = NULL
        WHERE CartId = @GuestCartId;

        RETURN;
    END

    INSERT INTO CartItem (CartId, ProductId, Quantity, UnitPrice)
    SELECT
        @UserCartId,
        ProductId,
        Quantity,
        UnitPrice
    FROM CartItem gc
    WHERE gc.CartId = @GuestCartId
      AND NOT EXISTS (
          SELECT 1 FROM CartItem uc
          WHERE uc.CartId = @UserCartId
            AND uc.ProductId = gc.ProductId
      );

    DELETE FROM CartItem WHERE CartId = @GuestCartId;
    DELETE FROM Cart WHERE CartId = @GuestCartId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Cart_RemoveItem]...';


GO
CREATE PROCEDURE SP_Cart_RemoveItem
(
    @CartId BIGINT,
    @ProductId BIGINT
)
AS
BEGIN
    DELETE FROM CartItem
    WHERE CartId = @CartId AND ProductId = @ProductId;

    UPDATE Cart SET UpdatedOn = GETDATE() WHERE CartId = @CartId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Cart_UpdateQuantity]...';


GO
CREATE PROCEDURE [dbo].[SP_Cart_UpdateQuantity]
(
    @UserId BIGINT,
    @ProductId BIGINT,
    @Quantity INT
)
AS
BEGIN
    SET NOCOUNT ON;

    IF @Quantity < 0
    BEGIN
        RAISERROR('Quantity cannot be negative',16,1);
        RETURN;
    END

    DECLARE @CartId BIGINT;

    SELECT @CartId = CartId
    FROM Cart
    WHERE UserId = @UserId
      AND Status = 'ACTIVE';

    IF @CartId IS NULL
    BEGIN
        RAISERROR('Active cart not found',16,1);
        RETURN;
    END

    IF @Quantity = 0
    BEGIN
        DELETE FROM CartItem
        WHERE CartId = @CartId
          AND ProductId = @ProductId;

        RETURN;
    END

    UPDATE CartItem
    SET Quantity = @Quantity,
        UpdatedOn = SYSDATETIME()
    WHERE CartId = @CartId
      AND ProductId = @ProductId;

    IF @@ROWCOUNT = 0
    BEGIN
        RAISERROR('Cart item not found',16,1);
        RETURN;
    END

    UPDATE Cart
    SET UpdatedOn = SYSDATETIME()
    WHERE CartId = @CartId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Checkout_ConfirmCOD_Backup]...';


GO
CREATE PROCEDURE [dbo].[SP_Checkout_ConfirmCOD_Backup]
(
    @UserId BIGINT,
	@CheckoutTransactionId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRAN;

        DECLARE
            @CheckoutTxnId BIGINT,
            @FinalPaymentTxnId BIGINT;
			
        /* 1️⃣ Get OPEN checkout */
        SELECT TOP 1
            @CheckoutTxnId = PaymentTransactionId
        FROM CheckOutPaymentTransactions
        WHERE UserId = @UserId
		AND PaymentTransactionId = @CheckoutTransactionId
        AND OrderStatus = 'Open'
        ORDER BY CreatedOn DESC;

        IF @CheckoutTxnId IS NULL
        BEGIN
            RAISERROR ('No open checkout found for COD', 16, 1);
            ROLLBACK TRAN;
            RETURN;
        END
		
        /* 2️⃣ Create FINAL payment transaction */
        INSERT INTO PaymentTransactions
        (
            UserId,
            PaymentMode,
            TxnStatus,
            PaymentStatus,
            CreatedOn,
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            TxnAmount,
			TxnMessage,
			Authorized,
			OrderCurrentStatus,
			ShippingCharges
        )
        SELECT
            UserId,
            'Cash On Delivery',
            'SUCCESS',
            1,
            SYSDATETIME(),
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            TxnAmount,
			'Transaction Successful through COD',
			1,
			6,
			ShippingCharges
        FROM CheckOutPaymentTransactions
        WHERE PaymentTransactionId = @CheckoutTxnId;

        SET @FinalPaymentTxnId = SCOPE_IDENTITY();

        /* 3️⃣ Move checkout items → final order items */
        INSERT INTO UserProductTransactions
(
    PaymentTransactionId,
    UserId,
    ProductId,
    SubProductId,
    Quantity,
    ProductCost,
    ProductDiscountPercentage,
    ProductDiscountCost,
    ShippingAddressId,
    BillingAddressId,
    IsActive,
    IsDeleted,
    CreatedOn,
    UpdatedOn,
    CreatedBy,
    UpdatedBy,
    Status,

    -- ✅ REQUIRED LEGACY COLUMNS
    CurrencyCode,
    CurrencyValue,
    CurrencySymbol,

    OrdersReturnReason,
    OrdersReturnAction,
    ReplacementTransactionId,
    IsReplaced,
	ExpectedDeliveryDate
)
SELECT
    @FinalPaymentTxnId,
    cup.UserId,
    cup.ProductId,
    cup.SubProductId,
    cup.Quantity,
    cup.ProductCost,
    ISNULL(cup.ProductDiscountPercentage, 0),
    ISNULL(cup.ProductDiscountCost, 0),
    cup.ShippingAddressId,
    cup.BillingAddressId,
    1,
    0,
    SYSDATETIME(),
    SYSDATETIME(),
    cup.CreatedBy,
    cup.UpdatedBy,
    cup.Status,

    -- ✅ COPY FROM CHECKOUT (NOT NULL GUARANTEED)
    chk.CurrencyCode,
    chk.CurrencyValue,
    chk.CurrencySymbol,

    cup.OrdersReturnReason,
    cup.OrdersReturnAction,
    cup.ReplacementTransactionId,
    cup.IsReplaced,
	cup.ExpectedDeliveryDate
FROM CheckOutUserProductTransactions cup
INNER JOIN CheckOutPaymentTransactions chk
    ON chk.PaymentTransactionId = cup.PaymentTransactionId
WHERE cup.PaymentTransactionId = @CheckoutTxnId;

        /* 4️⃣ Close checkout */
        UPDATE CheckOutPaymentTransactions
        SET
            OrderStatus = 'Closed',
            UpdatedOn = SYSDATETIME()
        WHERE PaymentTransactionId = @CheckoutTxnId;

        /* 5️⃣ Clear cart */
        DELETE CI
        FROM CartItem CI
        INNER JOIN Cart C ON CI.CartId = C.CartId
        WHERE C.UserId = @UserId;

        UPDATE Cart
        SET Status = 'CHECKED_OUT',
            UpdatedOn = SYSDATETIME()
        WHERE UserId = @UserId
          AND Status = 'ACTIVE';


		  /* 6️⃣ Attach prescriptions to order */
UPDATE Tbl_Presecription_Info
SET Payment_Transaction_Id = @FinalPaymentTxnId
WHERE User_Id = @UserId
AND Payment_Transaction_Id IS NULL;


        COMMIT TRAN;

        SELECT @FinalPaymentTxnId AS PaymentTransactionId;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[SP_Checkout_GetOpen]...';


GO
CREATE   PROCEDURE dbo.SP_Checkout_GetOpen
(
    @UserId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TOP 1
        c.PaymentTransactionId,

        -- 🔹 Split for UI compatibility
        (c.TxnAmount - c.ShippingCharges) AS OrderAmount,
        c.TxnAmount AS PayableAmount,

        c.ShippingCharges,
        c.CurrencyCode,
        c.CurrencySymbol,
        c.CurrencyValue,
        c.PaymentMode,
        c.Promo_Code_ID,
        c.Promo_Code_Amount,
        c.TxnStatus,
        c.OrderStatus,

        u.FirstName,
        u.EmailId AS Email,
        u.MobileNo AS Mobile

    FROM CheckOutPaymentTransactions c
    INNER JOIN Users u ON c.UserId = u.UserId
    WHERE c.UserId = @UserId
      AND c.OrderStatus = 'Open'
    ORDER BY c.CreatedOn DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Checkout_GetSummary]...';


GO
CREATE PROCEDURE dbo.SP_Checkout_GetSummary
(
    @UserId BIGINT
)
AS
BEGIN
    SELECT TOP 1
        PaymentTransactionId,
        TxnAmount,
        ShippingCharges,
        (TxnAmount + ShippingCharges) AS PayableAmount,
        CurrencyCode,
        CurrencySymbol,
        PaymentMode,
        TxnStatus,
        OrderStatus
    FROM CheckOutPaymentTransactions
    WHERE UserId = @UserId
    ORDER BY CreatedOn DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Checkout_UpsertAndCalculate_backup]...';


GO
CREATE PROCEDURE [dbo].[SP_Checkout_UpsertAndCalculate_backup]
(
    @UserId BIGINT,
    @PaymentMode NVARCHAR(50),
    @ShippingAddressId BIGINT,
    @BillingAddressId BIGINT,
    @CouponId BIGINT = NULL,
	@ExpectedDeliveryDate DATETIME,

    -- Currency (legacy-compatible)
    @CurrencyCode NVARCHAR(10),
    @CurrencySymbol NVARCHAR(5),
    @CurrencyValue DECIMAL(18,6)
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRAN;

        /* ------------------------------
           0️⃣ Validation
        ------------------------------ */
        IF @ShippingAddressId IS NULL OR @BillingAddressId IS NULL
        BEGIN
            RAISERROR ('Shipping and Billing Address are mandatory for checkout', 16, 1);
            ROLLBACK TRAN;
            RETURN;
        END

        DECLARE 
            @PaymentTransactionId BIGINT,
            @SubTotal MONEY = 0,
            @ShippingCharges MONEY = 0,
            @CouponAmount MONEY = 0,
            @FinalAmount MONEY = 0;

        /* ------------------------------
           1️⃣ Create or reuse OPEN checkout
        ------------------------------ */
        SELECT TOP 1
            @PaymentTransactionId = PaymentTransactionId
        FROM CheckOutPaymentTransactions
        WHERE UserId = @UserId
          AND OrderStatus = 'Open'
        ORDER BY CreatedOn DESC;

        IF @PaymentTransactionId IS NULL
        BEGIN
            INSERT INTO CheckOutPaymentTransactions
            (
                UserId,
                CreatedOn,
                TxnStatus,
                PaymentStatus,
                OrderStatus,
                OrderCurrentStatus,
                PaymentMode,
                CurrencyCode,
                CurrencySymbol,
                CurrencyValue
            )
            VALUES
            (
                @UserId,
                SYSDATETIME(),
                'Checkout',
                0,
                'Open',
                10,
                @PaymentMode,
                @CurrencyCode,
                @CurrencySymbol,
                @CurrencyValue
            );

            SET @PaymentTransactionId = SCOPE_IDENTITY();
        END

        /* ------------------------------
           2️⃣ Cart Subtotal
        ------------------------------ */
        SELECT
            @SubTotal = SUM(ci.UnitPrice * ci.Quantity)
        FROM CartItem ci
        INNER JOIN Cart c ON ci.CartId = c.CartId
        WHERE c.UserId = @UserId
          AND c.Status = 'ACTIVE';

        /* ------------------------------
           3️⃣ Shipping Rules (LEGACY)
        ------------------------------ */
        IF (@PaymentMode = 'Cash On Delivery')
        BEGIN
            IF (@SubTotal < 1000)
                SET @ShippingCharges = 150;
            ELSE IF (@SubTotal <= 2000)
                SET @ShippingCharges = 100;
            ELSE
                SET @ShippingCharges = 50;
        END
        ELSE
        BEGIN
            IF (@SubTotal <= 500)
                SET @ShippingCharges = 50;
            ELSE
                SET @ShippingCharges = 0;
        END

        /* ------------------------------
           4️⃣ Coupon Logic (LEGACY)
        ------------------------------ */
        IF @CouponId IS NOT NULL
        BEGIN
            SELECT
                @CouponAmount =
                    CASE
                        WHEN Coupon_Percentage = 0
                            THEN Coupon_Amount
                        ELSE ROUND((Coupon_Percentage * @SubTotal) / 100, 0)
                    END
            FROM Tbl_Coupon_Info
            WHERE Coupon_Id = @CouponId;
        END

        SET @FinalAmount = @SubTotal + @ShippingCharges - ISNULL(@CouponAmount, 0);

        /* ------------------------------
           5️⃣ Update Checkout Summary
        ------------------------------ */
        UPDATE CheckOutPaymentTransactions
        SET
            TxnAmount         = @FinalAmount,
            ShippingCharges   = @ShippingCharges,
            Promo_Code_ID     = @CouponId,
            Promo_Code_Amount = @CouponAmount,
            PaymentMode       = @PaymentMode,
            UpdatedOn         = SYSDATETIME()
        WHERE PaymentTransactionId = @PaymentTransactionId;

        /* ------------------------------
           6️⃣ Snapshot Cart → Checkout Items
        ------------------------------ */
        DELETE FROM CheckOutUserProductTransactions
        WHERE PaymentTransactionId = @PaymentTransactionId;

        INSERT INTO CheckOutUserProductTransactions
        (
            PaymentTransactionId,
            UserId,
            ProductId,
            SubProductId,
            Quantity,
            ProductCost,
            ProductDiscountPercentage,
            ProductDiscountCost,
            ShippingAddressId,
            BillingAddressId,
            IsActive,
            IsDeleted,
            CreatedOn,
            UpdatedOn,
            CreatedBy,
            UpdatedBy,
            Status,
            CurrencyCode,
            CurrencyValue,
            CurrencySymbol,
            OrdersReturnReason,
            OrdersReturnAction,
            ReplacementTransactionId,
            IsReplaced,
			ExpectedDeliveryDate
        )
        SELECT
            @PaymentTransactionId,
            @UserId,
            ci.ProductId,
            NULL,
            ci.Quantity,
            ci.UnitPrice * ci.Quantity,
            ISNULL(p.ProductDiscountPercentage, 0),
            ISNULL(p.ProductDiscountCost, 0),
            @ShippingAddressId,
            @BillingAddressId,
            1,
            0,
            SYSDATETIME(),
            SYSDATETIME(),
            @UserId,
            @UserId,
            0,
            @CurrencyCode,
            @CurrencyValue,
            @CurrencySymbol,
            NULL,
            NULL,
            0,
            0,
			@ExpectedDeliveryDate
        FROM CartItem ci
        INNER JOIN Cart c ON ci.CartId = c.CartId
        INNER JOIN Products p ON ci.ProductId = p.ProductId
        WHERE c.UserId = @UserId
          AND c.Status = 'ACTIVE';

        COMMIT TRAN;

        /* ------------------------------
           7️⃣ Return
        ------------------------------ */
        SELECT 
            @PaymentTransactionId AS PaymentTransactionId,
            @FinalAmount AS PayableAmount,
            @ShippingCharges AS ShippingCharges;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[SP_Coupon_ValidateAndApply]...';


GO
CREATE   PROCEDURE dbo.SP_Coupon_ValidateAndApply
(
    @CouponId BIGINT,
    @UserId BIGINT,
    @CartId BIGINT = NULL,
    @SubTotal DECIMAL(18,2),

    @Recalculate BIT = 1,           -- 1=compute amount, 0=trust incoming amount
    @SyncCart BIT = 0,              -- if invalid, clear cart coupon
    @SyncCheckout BIT = 0,          -- if invalid, clear checkout coupon
    @CheckoutTxnId BIGINT = NULL,

    @IsValid BIT OUTPUT,
    @CouponAmount DECIMAL(18,2) OUTPUT,
    @ErrorMessage NVARCHAR(200) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE
        @ValidFrom DATETIME,
        @ValidTo DATETIME,
        @MinCartValue DECIMAL(18,2),
        @CouponPercentage DECIMAL(18,2),
        @FixedAmount DECIMAL(18,2);

    SET @IsValid = 0;
    SET @CouponAmount = 0;
    SET @ErrorMessage = NULL;

    SELECT
        @ValidFrom = Valid_From,
        @ValidTo = Valid_To,
        @MinCartValue = Min_Cart_Value,
        @CouponPercentage = Coupon_Percentage,
        @FixedAmount = Coupon_Amount
    FROM Tbl_Coupon_Info
    WHERE Coupon_Id = @CouponId
      AND Status = 1;

    IF @ValidFrom IS NULL
    BEGIN
        SET @ErrorMessage = 'Invalid coupon';
        GOTO INVALID;
    END

    IF GETDATE() NOT BETWEEN @ValidFrom AND @ValidTo
    BEGIN
        SET @ErrorMessage = 'Coupon expired';
        GOTO INVALID;
    END

    IF @MinCartValue IS NOT NULL AND @SubTotal < @MinCartValue
    BEGIN
        SET @ErrorMessage = 'Minimum cart value not met';
        GOTO INVALID;
    END

    IF @Recalculate = 1
    BEGIN
        IF @CouponPercentage IS NOT NULL AND @CouponPercentage > 0
            SET @CouponAmount = ROUND((@SubTotal * @CouponPercentage)/100.0, 2);
        ELSE
            SET @CouponAmount = ISNULL(@FixedAmount, 0);
    END

    SET @IsValid = 1;
    RETURN;

INVALID:
    IF @SyncCart = 1 AND @CartId IS NOT NULL
    BEGIN
        UPDATE Cart
        SET Has_Promo_Code = 0,
            Promo_Code_ID = NULL,
            Promo_Code_Amount = NULL,
            UpdatedOn = SYSDATETIME()
        WHERE CartId = @CartId;
    END

    IF @SyncCheckout = 1 AND @CheckoutTxnId IS NOT NULL
    BEGIN
        UPDATE CheckOutPaymentTransactions
        SET Has_Promo_Code = 0,
            Promo_Code_ID = NULL,
            Promo_Code_Amount = NULL,
            UpdatedOn = SYSDATETIME()
        WHERE PaymentTransactionId = @CheckoutTxnId;
    END
END
GO
PRINT N'Creating Procedure [dbo].[SP_Discovery_Navigation]...';


GO
CREATE   PROCEDURE dbo.SP_Discovery_Navigation
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        sc.SuperCategoryId,
        sc.SuperCategoryName,
        c.CategoryId,
        c.CategoryName,
        sub.SubCategoryId,
        sub.SubCategoryName
    FROM SuperCategories sc
    INNER JOIN Categories c
        ON c.SuperCategoryId = sc.SuperCategoryId
    INNER JOIN SubCategories sub
        ON sub.CategoryId = c.CategoryId
    ORDER BY
        sc.SuperCategoryName,
        c.CategoryName,
        sub.SubCategoryName;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Discovery_ProductsByCategoryGroup]...';


GO
CREATE   PROCEDURE dbo.SP_Discovery_ProductsByCategoryGroup
(
    @TopProductsPerCategory INT = 8
)
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH RankedProducts AS
    (
        SELECT
            sc.SuperCategoryId,
            sc.SuperCategoryName,

            c.CategoryId,
            c.CategoryName,

            p.ProductId,
            p.ProductName,
           -- p.Price,
           -- p.ImageUrl,

            ROW_NUMBER() OVER
            (
                PARTITION BY c.CategoryId
                ORDER BY p.CreatedOn DESC
            ) AS ProductRank
        FROM SuperCategories sc
        INNER JOIN Categories c
            ON c.SuperCategoryId = sc.SuperCategoryId
        INNER JOIN SubCategories sub
            ON sub.CategoryId = c.CategoryId
        INNER JOIN Products p
            ON p.SubCategoryId = sub.SubCategoryId
        WHERE
            p.IsActive = 1
            AND p.IsDeleted = 0
            AND p.Quantity > 0
    )
    SELECT
        SuperCategoryId,
        SuperCategoryName,
        CategoryId,
        CategoryName,
        ProductId,
        ProductName
      --  Price,
      --  ImageUrl
    FROM RankedProducts
    WHERE ProductRank <= @TopProductsPerCategory
    ORDER BY SuperCategoryId, CategoryId, ProductRank;
END
GO
PRINT N'Creating Procedure [dbo].[SP_GetBrandsByCategory]...';


GO
CREATE PROCEDURE [dbo].[SP_GetBrandsByCategory]
(
    @CategoryId INT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        p.Brand AS [BrandName],
        COUNT(p.Brand) AS [Count]
    FROM dbo.Products p
    INNER JOIN dbo.SubCategories sc ON p.SubCategoryId = sc.SubCategoryId
    WHERE
        p.IsActive = 1
        AND p.IsDeleted = 0
        AND p.Quantity > 0
        AND sc.CategoryId = @CategoryId
        AND ISNULL(LTRIM(RTRIM(p.Brand)), '') <> ''
    GROUP BY p.Brand
    ORDER BY p.Brand ASC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_GetBrandsBySubCategory]...';


GO

CREATE PROCEDURE [dbo].[SP_GetBrandsBySubCategory] ( @SubCategoryId INT ) AS BEGIN SET NOCOUNT ON;
SELECT
    p.Brand AS [BrandName],
    COUNT(p.Brand) AS [Count]
FROM dbo.Products p
INNER JOIN dbo.SubCategories sc ON p.SubCategoryId = sc.SubCategoryId
WHERE
    p.IsActive = 1
    AND p.IsDeleted = 0
    AND p.Quantity > 0
    AND sc.SubCategoryId = @SubCategoryId
    AND ISNULL(LTRIM(RTRIM(p.Brand)), '') <> ''
GROUP BY p.Brand ORDER BY p.Brand ASC
END
GO
PRINT N'Creating Procedure [dbo].[SP_GetBrandsWithCount]...';


GO
CREATE PROCEDURE [dbo].[SP_GetBrandsWithCount]
AS
BEGIN
    SET NOCOUNT ON;
   SELECT  Brand as [BrandName], count (Brand) as [Count] from [dbo].[Products] group by Brand order by Brand asc
END
GO
PRINT N'Creating Procedure [dbo].[SP_Impersonation_Audit_Insert]...';


GO
CREATE PROCEDURE SP_Impersonation_Audit_Insert
(
    @SupportUserId BIGINT,
    @CustomerUserId BIGINT,
    @Reason NVARCHAR(200),
    @IpAddress VARCHAR(50)
)
AS
BEGIN
    INSERT INTO ImpersonationAudit
    (
        SupportUserId,
        CustomerUserId,
        Reason,
        IpAddress,
        CreatedOn
    )
    VALUES
    (
        @SupportUserId,
        @CustomerUserId,
        @Reason,
        @IpAddress,
        GETUTCDATE()
    );
END
GO
PRINT N'Creating Procedure [dbo].[SP_Order_GetStatusTimeline]...';


GO
CREATE PROCEDURE SP_Order_GetStatusTimeline
(
    @PaymentTransactionId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        PaymentTransactionId,

        CreatedOn AS OrderPlacedDate,

        CASE WHEN Authorized = 1
             THEN CreatedOn
        END AS ProcessingDate,

        CASE WHEN Dispatched = 1
             THEN DispatchedDate
        END AS DispatchedDate,

        CASE WHEN Delivered = 1
             THEN DeliveredDate
        END AS DeliveredDate,

        CASE WHEN TxnStatus = 'Transaction Failed'
             THEN UpdatedOn
        END AS CancelledDate,

        OrderCurrentStatus

    FROM PaymentTransactions
    WHERE PaymentTransactionId = @PaymentTransactionId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_OrderDetails_GetById]...';


GO
CREATE PROCEDURE [dbo].[SP_OrderDetails_GetById]
(
    @Id INT
)
AS
BEGIN
    SET NOCOUNT ON;

SELECT 
    upt.PaymentTransactionId AS OrderId,
    pt.ShipmentDate AS OrderDate,
    upt.ProductName,
    upt.Quantity,
    upt.ProductCost AS Price,
    (pt.CGST + pt.SGST) AS GST,
    (upt.ProductCost * upt.Quantity + pt.CGST + pt.SGST) AS Total
FROM UserProductTransactions upt
INNER JOIN PaymentTransactions pt 
    ON upt.PaymentTransactionId = pt.PaymentTransactionId
    LEFT JOIN ProductsGallery pg 
    ON upt.ProductId = pg.ProductId 
    AND pg.IsActive = 1 
    AND pg.IsDeleted = 0
WHERE upt.PaymentTransactionId = @Id
ORDER BY upt.PaymentTransactionId DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_OrderDetails_GetByUserId]...';


GO
CREATE PROCEDURE [dbo].[SP_OrderDetails_GetByUserId]
(
    @UserId INT
)
AS
BEGIN
    SET NOCOUNT ON;

SELECT 
    upt.PaymentTransactionId AS OrderId,
    pt.ShipmentDate AS OrderDate,
    upt.ProductName,
    upt.Quantity,
    upt.ProductCost AS Price,
    (pt.CGST + pt.SGST) AS GST,
    (upt.ProductCost * upt.Quantity + pt.CGST + pt.SGST) AS Total
FROM UserProductTransactions upt
INNER JOIN PaymentTransactions pt 
    ON upt.PaymentTransactionId = pt.PaymentTransactionId
WHERE upt.UserId = @UserId
ORDER BY upt.PaymentTransactionId DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Orders_GetByUserId]...';


GO

CREATE PROCEDURE [dbo].[SP_Orders_GetByUserId]
(
    @UserId INT
)
AS
BEGIN
    SET NOCOUNT ON;

SELECT 
    pt.PaymentTransactionId,   
    pt.UserId,                 
    pt.TxnAmount,              
    pt.PaymentMode,            
    pt.PaymentStatus,          
    pt.OrderCurrentStatus     
FROM PaymentTransactions pt
WHERE pt.UserId = @UserId
ORDER BY pt.PaymentTransactionId DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Payment_ConfirmOnlineSuccess]...';


GO
CREATE PROCEDURE [dbo].[SP_Payment_ConfirmOnlineSuccess]
(
    @UserId BIGINT,
    @CheckoutTxnId BIGINT,
    @GatewayTransactionId NVARCHAR(200),
    @PaymentMode NVARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE 
            @FinalPaymentTxnId BIGINT,
            @CouponId BIGINT,
            @CouponAmount DECIMAL(18,2),
            @HasPromo BIT,
            @SubTotal DECIMAL(18,2),
            @ShippingCharges DECIMAL(18,2),
            @FinalAmount DECIMAL(18,2),
            @IsValid BIT,
            @Err NVARCHAR(200);

        --------------------------------------------------
        -- 1. Validate Checkout
        --------------------------------------------------
        SELECT
            @CouponId = Promo_Code_ID,
            @CouponAmount = ISNULL(Promo_Code_Amount, 0),
            @HasPromo = ISNULL(Has_Promo_Code, 0),
            @ShippingCharges = ISNULL(ShippingCharges, 0)
        FROM CheckOutPaymentTransactions
        WHERE PaymentTransactionId = @CheckoutTxnId
          AND UserId = @UserId
          AND OrderStatus = 'Open';

        IF @@ROWCOUNT = 0
        BEGIN
            RAISERROR ('Invalid or already processed checkout',16,1);
            ROLLBACK TRANSACTION;
            RETURN;
        END

        --------------------------------------------------
        -- 2. Subtotal
        --------------------------------------------------
        SELECT @SubTotal = SUM(ProductCost)
        FROM CheckOutUserProductTransactions
        WHERE PaymentTransactionId = @CheckoutTxnId;

        IF @SubTotal IS NULL SET @SubTotal = 0;

        --------------------------------------------------
        -- 3. Coupon via Engine
        --------------------------------------------------
        IF @CouponId IS NOT NULL AND @HasPromo = 1
        BEGIN
            EXEC dbo.SP_Coupon_ValidateAndApply
                @CouponId = @CouponId,
                @UserId = @UserId,
                @CartId = NULL,
                @SubTotal = @SubTotal,
                @Recalculate = 0,
                @SyncCart = 1,
                @SyncCheckout = 1,
                @CheckoutTxnId = @CheckoutTxnId,
                @IsValid = @IsValid OUTPUT,
                @CouponAmount = @CouponAmount OUTPUT,
                @ErrorMessage = @Err OUTPUT;

            IF @IsValid = 0
            BEGIN
                SET @CouponId = NULL;
                SET @CouponAmount = 0;
                SET @HasPromo = 0;
            END
        END

        --------------------------------------------------
        -- 4. Final Amount
        --------------------------------------------------
        SET @FinalAmount = @SubTotal + @ShippingCharges - @CouponAmount;
        IF @FinalAmount < 0 SET @FinalAmount = 0;

        --------------------------------------------------
        -- 5. Insert Payment
        --------------------------------------------------
        INSERT INTO PaymentTransactions
        (
            UserId, PaymentMode, TxnStatus, PaymentStatus, CreatedOn,
            PGTxnId, CurrencyCode, CurrencySymbol, CurrencyValue,
            TxnAmount, TxnMessage, Authorized, OrderCurrentStatus,
            ShippingCharges, Has_Promo_Code, Promo_Code_ID, Promo_Code_Amount
        )
        SELECT
            UserId,
            @PaymentMode,
            'SUCCESS',
            1,
            SYSDATETIME(),
            @GatewayTransactionId,
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            @FinalAmount,
            'Transaction Successful through Payment Gateway',
            1,
            6,
            @ShippingCharges,
            @HasPromo,
            @CouponId,
            CASE WHEN @HasPromo = 1 THEN @CouponAmount ELSE NULL END
        FROM CheckOutPaymentTransactions
        WHERE PaymentTransactionId = @CheckoutTxnId;

        SET @FinalPaymentTxnId = SCOPE_IDENTITY();

		--------------------------------------------------
        -- 6. Move snapshot → final order items
        --------------------------------------------------
		INSERT INTO UserProductTransactions
        (
            PaymentTransactionId,
            UserId,
            ProductId,
            SubProductId,
            Quantity,

            ProductOriginalCost,
            ProductCost,
            ProductDiscountPercentage,
            ProductDiscountCost,

            ShippingAddressId,
            BillingAddressId,
            IsActive,
            IsDeleted,
            CreatedOn,
            UpdatedOn,
            CreatedBy,
            UpdatedBy,
            Status,

            CurrencyCode,
            CurrencyValue,
            CurrencySymbol,

            OrdersReturnReason,
            OrdersReturnAction,
            ReplacementTransactionId,
            IsReplaced,

			ExpectedDeliveryDate,

			GST_Percentage,
			GST_Amount,
			CGST,
			SGST,
			IGST,
			BaseAmount
        )
		SELECT
             @FinalPaymentTxnId,
            cup.UserId,
            cup.ProductId,
            cup.SubProductId,
            cup.Quantity,

             p.ProductOriginalCost,
            cup.ProductCost,
            ISNULL(cup.ProductDiscountPercentage, 0),
            ISNULL(cup.ProductDiscountCost, 0),

            cup.ShippingAddressId,
            cup.BillingAddressId,
            1,
            0,
            SYSDATETIME(),
            SYSDATETIME(),
            cup.CreatedBy,
            cup.UpdatedBy,
            0,

            chk.CurrencyCode,
            chk.CurrencyValue,
            chk.CurrencySymbol,

            cup.OrdersReturnReason,
            cup.OrdersReturnAction,
            cup.ReplacementTransactionId,
            cup.IsReplaced,

            cup.ExpectedDeliveryDate,

			p.GST,
			gst.GST_Amount,
			gst.CGST,
			gst.SGST,
			gst.IGST,
			gst.BaseAmount
		 FROM CheckOutUserProductTransactions cup
        INNER JOIN CheckOutPaymentTransactions chk
            ON chk.PaymentTransactionId = cup.PaymentTransactionId
        INNER JOIN Products p
            ON p.ProductId = cup.ProductId
        INNER JOIN UserAddresses ua
            ON ua.UserAddressId = cup.ShippingAddressId
        CROSS APPLY dbo.fn_CalculateGST(
            cup.ProductCost,
            p.GST,
            ua.StateName
        ) gst
        WHERE cup.PaymentTransactionId = @CheckoutTxnId;

		--------------------------------------------------
        -- 7. Close checkout
        --------------------------------------------------
        UPDATE CheckOutPaymentTransactions
        SET OrderStatus = 'Closed',
            UpdatedOn = SYSDATETIME()
        WHERE PaymentTransactionId = @CheckoutTxnId;

		--------------------------------------------------
        -- 8. Clear Cart 
        --------------------------------------------------       
        DELETE CI
        FROM CartItem CI
        INNER JOIN Cart C ON CI.CartId = C.CartId
        WHERE C.UserId = @UserId;

        UPDATE Cart
        SET Status = 'CHECKED_OUT',
            UpdatedOn = SYSDATETIME()
        WHERE UserId = @UserId
          AND Status = 'ACTIVE';

		--------------------------------------------------
        -- 9. Attach prescriptions to order
        --------------------------------------------------
		UPDATE Tbl_Presecription_Info
		SET Payment_Transaction_Id = @FinalPaymentTxnId
		WHERE User_Id = @UserId
		AND Payment_Transaction_Id IS NULL;

        COMMIT TRANSACTION;

        SELECT @FinalPaymentTxnId AS PaymentTransactionId;

    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[SP_Payment_ConfirmOnlineSuccess_Backup]...';


GO
CREATE PROCEDURE [dbo].[SP_Payment_ConfirmOnlineSuccess_Backup]
(
    @UserId BIGINT,
    @CheckoutTxnId BIGINT,
    @GatewayTransactionId NVARCHAR(200),
    @PaymentMode NVARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @FinalPaymentTxnId BIGINT;

        /* 1️⃣ Validate checkout exists */
        IF NOT EXISTS (
            SELECT 1
            FROM CheckOutPaymentTransactions
            WHERE PaymentTransactionId = @CheckoutTxnId
              AND UserId = @UserId
              AND OrderStatus = 'Open'
        )
        BEGIN
            RAISERROR ('Invalid or already processed checkout',16,1);
            ROLLBACK TRANSACTION;
            RETURN;
        END

        /* 2️⃣ Insert into FINAL PaymentTransactions */
        INSERT INTO PaymentTransactions
        (
            UserId,
            PaymentMode,
            TxnStatus,
            PaymentStatus,
            CreatedOn,
            PGTxnId,
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            TxnAmount,
			TxnMessage,
			Authorized,
			OrderCurrentStatus,
			ShippingCharges
        )
        SELECT
            UserId,
            @PaymentMode,
            'SUCCESS',
            1,
            SYSDATETIME(),
            @GatewayTransactionId,
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            TxnAmount,
			'Transaction Successful through Pay_U',
			1,
			6,
			ShippingCharges
        FROM CheckOutPaymentTransactions
        WHERE PaymentTransactionId = @CheckoutTxnId;

        SET @FinalPaymentTxnId = SCOPE_IDENTITY();

        /* 3️⃣ Move snapshot → final order items */
        INSERT INTO UserProductTransactions
        (
            PaymentTransactionId,
            UserId,
            ProductId,
            SubProductId,
            Quantity,
            ProductCost,
            ProductDiscountPercentage,
            ProductDiscountCost,
            ShippingAddressId,
            BillingAddressId,
            IsActive,
            IsDeleted,
            CreatedOn,
            UpdatedOn,
            CreatedBy,
            UpdatedBy,
            Status,
            CurrencyCode,
            CurrencyValue,
            CurrencySymbol,
            OrdersReturnReason,
            OrdersReturnAction,
            ReplacementTransactionId,
            IsReplaced,
			ExpectedDeliveryDate
        )
		SELECT
            @FinalPaymentTxnId,
            UserId,
            ProductId,
            SubProductId,
            Quantity,
            ProductCost,
            ProductDiscountPercentage,
            ProductDiscountCost,
            ShippingAddressId,
            BillingAddressId,
            1,
            0,
            SYSDATETIME(),
            SYSDATETIME(),
            CreatedBy,
            UpdatedBy,
            0,
            CurrencyCode,
            CurrencyValue,
            CurrencySymbol,
            OrdersReturnReason,
            OrdersReturnAction,
            ReplacementTransactionId,
            IsReplaced,
			ExpectedDeliveryDate
		FROM CheckOutUserProductTransactions
        WHERE PaymentTransactionId = @CheckoutTxnId;

        /* 4️⃣ Close checkout */
        UPDATE CheckOutPaymentTransactions
        SET OrderStatus = 'Closed',
            UpdatedOn = SYSDATETIME()
        WHERE PaymentTransactionId = @CheckoutTxnId;

        /* 5️⃣ Clear Cart */
        DELETE CI
        FROM CartItem CI
        INNER JOIN Cart C ON CI.CartId = C.CartId
        WHERE C.UserId = @UserId;

        UPDATE Cart
        SET Status = 'CHECKED_OUT',
            UpdatedOn = SYSDATETIME()
        WHERE UserId = @UserId
          AND Status = 'ACTIVE';

		  /* 6️⃣ Attach prescriptions to order */
UPDATE Tbl_Presecription_Info
SET Payment_Transaction_Id = @FinalPaymentTxnId
WHERE User_Id = @UserId
AND Payment_Transaction_Id IS NULL;

        COMMIT TRANSACTION;

        SELECT @FinalPaymentTxnId AS PaymentTransactionId;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[SP_Payment_MarkFailed]...';


GO
CREATE PROCEDURE [dbo].[SP_Payment_MarkFailed]
(
    @UserId BIGINT,
    @PaymentTransactionId BIGINT,
    @PaymentMode NVARCHAR(50),
    @PGTxnId NVARCHAR(100)
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @FinalPaymentTxnId BIGINT;

        /* 1️⃣ Validate checkout exists */
        IF NOT EXISTS (
            SELECT 1
            FROM CheckOutPaymentTransactions
            WHERE PaymentTransactionId = @PaymentTransactionId
              AND UserId = @UserId
              AND OrderStatus = 'Open'
        )
        BEGIN
            RAISERROR ('Invalid or already processed checkout',16,1);
            ROLLBACK TRANSACTION;
            RETURN;
        END

        /* 2️⃣ Insert failed payment record */
        INSERT INTO PaymentTransactions
        (
            UserId,
            PaymentMode,
            TxnStatus,
            TxnMessage,
            PaymentStatus,
            CreatedOn,
            PGTxnId,
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            TxnAmount
        )
        SELECT
            UserId,
            @PaymentMode,
            'FAILED',
            'Transaction Failed through ' + @PaymentMode,
            3,  -- legacy canceled enum
            SYSDATETIME(),
            @PGTxnId,
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            TxnAmount
        FROM CheckOutPaymentTransactions
        WHERE PaymentTransactionId = @PaymentTransactionId;

        SET @FinalPaymentTxnId = SCOPE_IDENTITY();

        /* 3️⃣ Update checkout status */
        UPDATE CheckOutPaymentTransactions
        SET
            OrderStatus = 'Failed',
            UpdatedOn = SYSDATETIME()
        WHERE PaymentTransactionId = @PaymentTransactionId;

        COMMIT TRANSACTION;

        SELECT @FinalPaymentTxnId AS PaymentTransactionId;

    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[SP_Prescription_InsertMultiple]...';


GO

CREATE PROCEDURE SP_Prescription_InsertMultiple
(
    @UserId BIGINT,
    @Images PrescriptionImageList READONLY
)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO Tbl_Presecription_Info
    (
        User_Id,
        Prescription_Image,
        Status,
        Created_Date
    )
    SELECT
        @UserId,
        ImageUrl,
        1,
        SYSDATETIME()
    FROM @Images;

    SELECT @@ROWCOUNT AS InsertedCount;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_Collections_NonTransactional]...';


GO
CREATE   PROCEDURE [dbo].[SP_Product_Collections_NonTransactional]
(
    @CollectionType VARCHAR(30), -- FEATURED | LATEST | CARONA
    @TopN INT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TOP (@TopN)
        p.ProductId,
        p.ProductName,
        p.ProductCost,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductDiscountCost,
        p.ProductImgUrl,
        p.ProductImgUrl2,
		p.Brand
    FROM Products p
    WHERE
        p.IsActive = 1
        AND p.IsDeleted = 0
        AND p.Quantity > 0
        AND p.IsSold = 0
        AND
        (
            -- FEATURED
            (@CollectionType = 'FEATURED'
             AND p.IsFeaturedProduct = 1)

            OR

            -- LATEST
            (@CollectionType = 'LATEST')

            OR

            -- CARONA (hardcoded legacy subcategories)
            (@CollectionType = 'CARONA'
             AND p.SubCategoryId IN (7, 8, 9, 23, 25, 212))
        )
    ORDER BY
        p.CreatedOn DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_Collections_Transactional]...';


GO
CREATE   PROCEDURE [dbo].[SP_Product_Collections_Transactional]
(
    @CollectionType VARCHAR(30), -- BEST_SOLD
    @TopN INT,
    @MinSalesCount INT
)
AS
BEGIN
    SET NOCOUNT ON;

    IF (@CollectionType <> 'BEST_SOLD')
        RETURN;

    SELECT TOP (@TopN)
        p.ProductId,
        p.ProductName,
        p.ProductCost,
		p.Brand,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductDiscountCost,
        p.ProductImgUrl,
        p.ProductImgUrl2
    FROM UserProductTransactions upt
    INNER JOIN Products p
        ON p.ProductId = upt.ProductId
    WHERE
        p.IsActive = 1
        AND p.IsDeleted = 0
        AND p.Quantity > 0
        AND p.IsSold = 0
        AND p.ProductId NOT IN (1367, 1811) -- legacy exclusions
    GROUP BY
        p.ProductId,
        p.ProductName,
        p.ProductCost,
		p.Brand,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductDiscountCost,
        p.ProductImgUrl,
        p.ProductImgUrl2
    HAVING
        COUNT(upt.ProductId) >= @MinSalesCount
    ORDER BY
        COUNT(upt.ProductId) DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetAdditionalInfo]...';


GO
CREATE PROCEDURE SP_Product_GetAdditionalInfo
(
    @ProductId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ProductId,
        Manufacturer_Date,
        Best_Before_Date,
        Country_Of_Origin,
        GTIN,
        Manufacturer_Details,
        Marketerdetails
    FROM Tbl_AdditionalInfo
    WHERE ProductId = @ProductId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetByBrand]...';


GO
CREATE PROCEDURE [dbo].[SP_Product_GetByBrand]
(
    @BrandName varchar(100)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        p.ProductId,
        p.ProductName,
        p.Brand,
        p.ProductCost,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductImgUrl,
        p.Quantity,
        p.IsFeaturedProduct,
        p.IsSold,
        p.UpdatedOn
    FROM Products p
   
    WHERE
        p.IsActive = 1
        AND p.IsDeleted = 0
        AND p.Quantity > 0
        AND p.Brand = @BrandName
    ORDER BY p.UpdatedOn DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetByCategoryAndBrand]...';


GO
CREATE PROCEDURE [dbo].[SP_Product_GetByCategoryAndBrand]
(
    @CategoryId INT,
    @BrandName NVARCHAR(200)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        p.ProductId,
        p.ProductName,
        p.Brand,
        p.ProductCost,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductImgUrl,
        p.Quantity,
        p.IsFeaturedProduct,
        p.IsSold,
        p.UpdatedOn,

        c.CategoryId,
        c.CategoryName,

        sc.SubCategoryId,
        sc.SubCategoryName
    FROM Products p
    INNER JOIN SubCategories sc ON p.SubCategoryId = sc.SubCategoryId
    INNER JOIN Categories c ON sc.CategoryId = c.CategoryId
    WHERE
        p.IsActive = 1
        AND p.IsDeleted = 0
        AND p.Quantity > 0
        AND c.CategoryId = @CategoryId
        AND LTRIM(RTRIM(p.Brand)) = @BrandName
    ORDER BY p.UpdatedOn DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetByCategoryId]...';


GO
CREATE PROCEDURE [dbo].[SP_Product_GetByCategoryId]
(
    @CategoryId INT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        p.ProductId,
        p.ProductName,
        p.Brand,
        p.ProductCost,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductImgUrl,
        p.Quantity,
        p.IsFeaturedProduct,
        p.IsSold,
        p.UpdatedOn,

        c.CategoryId,
        c.CategoryName,

        sc.SubCategoryId,
        sc.SubCategoryName
    FROM Products p
    INNER JOIN SubCategories sc ON p.SubCategoryId = sc.SubCategoryId
    INNER JOIN Categories c ON sc.CategoryId = c.CategoryId
    WHERE
        p.IsActive = 1
        AND p.IsDeleted = 0
        AND p.Quantity > 0
        AND c.CategoryId = @CategoryId
    ORDER BY p.UpdatedOn DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetById]...';


GO
CREATE PROCEDURE [dbo].[SP_Product_GetById]
(
    @ProductId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

        SELECT
        p.ProductId,
        p.ProductName,
        p.ProductDescription,
        p.ProductCost,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.Quantity,
        p.ProductImgUrl,
        p.ProductImgUrl2,
        p.Brand,
        p.ShortDescription,
        p.GST,
        p.ShippingCost,
		p.IsPresciption,

        ai.Manufacturer_Date,
        ai.Manufacturer_Details,
        ai.Best_Before_Date

    FROM Products p
    LEFT JOIN Tbl_AdditionalInfo ai
        ON p.ProductId = ai.ProductId

    WHERE p.ProductId = @ProductId
      AND p.IsDeleted = 0
      AND p.IsActive = 1;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetBySubCategoryAndBrand]...';


GO
CREATE PROCEDURE [dbo].[SP_Product_GetBySubCategoryAndBrand]
(
    @SubCategoryId INT,
    @BrandName NVARCHAR(200)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        p.ProductId,
        p.ProductName,
        p.Brand,
        p.ProductCost,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductImgUrl,
        p.Quantity,
        p.IsFeaturedProduct,
        p.IsSold,
        p.UpdatedOn,

        c.CategoryId,
        c.CategoryName,

        sc.SubCategoryId,
        sc.SubCategoryName
    FROM Products p
    INNER JOIN SubCategories sc ON p.SubCategoryId = sc.SubCategoryId
    INNER JOIN Categories c ON sc.CategoryId = c.CategoryId
    WHERE
        p.IsActive = 1
        AND p.IsDeleted = 0
        AND p.Quantity > 0
        AND sc.SubCategoryId = @SubCategoryId
        AND LTRIM(RTRIM(p.Brand)) = @BrandName
    ORDER BY p.UpdatedOn DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetBySubCategoryId]...';


GO
CREATE PROCEDURE [dbo].[SP_Product_GetBySubCategoryId]
(
    @SubCategoryId INT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        p.ProductId,
        p.ProductName,
        p.Brand,
        p.ProductCost,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductImgUrl,
        p.Quantity,
        p.IsFeaturedProduct,
        p.IsSold,
        p.UpdatedOn,

        c.CategoryId,
        c.CategoryName,

        sc.SubCategoryId,
        sc.SubCategoryName
    FROM Products p
    INNER JOIN SubCategories sc ON p.SubCategoryId = sc.SubCategoryId
    INNER JOIN Categories c ON sc.CategoryId = c.CategoryId
    WHERE
        p.IsActive = 1
        AND p.IsDeleted = 0
        AND p.Quantity > 0
        AND sc.SubCategoryId = @SubCategoryId
    ORDER BY p.UpdatedOn DESC;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetRelatedProducts]...';


GO
CREATE PROCEDURE [dbo].[SP_Product_GetRelatedProducts]
(
    @ProductId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        p.ProductId,
        p.ProductName,
        p.ProductCost,
        p.ProductOriginalCost,
        p.ProductDiscountPercentage,
        p.ProductDiscountCost,
        p.ProductImgUrl,
        p.ProductImgUrl2
    FROM RelatedProducts rp
    INNER JOIN Products p 
        ON rp.RelatedProductId = p.ProductId
    WHERE rp.ProductId = @ProductId
      AND p.IsActive = 1
      AND p.IsDeleted = 0;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_GetSubProducts]...';


GO
Create PROCEDURE [dbo].[SP_Product_GetSubProducts]
(
    @ProductId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ProductId          AS productId,
        SubProductId       AS subproductId,
        SPName             AS spName,
        ProductOriginalCost AS subproductoriginalcost,
        ProductDiscountPercentage AS subproductdiscountpercentage,
        ProductDiscountCost AS subproductdiscountcost,
        ProductCost        AS subproductcost,
        Quantity           AS subproductquantity
    FROM SubProducts
    WHERE ProductId = @ProductId;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Product_Search]...';


GO
CREATE PROCEDURE [dbo].[SP_Product_Search]
(
    @SearchText NVARCHAR(200)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TOP 50
        ProductId,
        ProductName,
        Brand,
        ProductCost,
        ProductImgUrl,
		ProductOriginalCost,
		ProductDiscountCost,
		ProductDiscountPercentage
    FROM Products
    WHERE IsActive = 1
      AND IsDeleted = 0
      AND (
            ProductName LIKE '%' + @SearchText + '%'
            OR Brand LIKE '%' + @SearchText + '%'
          )
    ORDER BY ProductName;
END
GO
PRINT N'Creating Procedure [dbo].[SP_User_GetById]...';


GO
CREATE PROCEDURE [dbo].[SP_User_GetById]
(
    @UserId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        FirstName,
        LastName,
        EmailId,
        MobileNo,
		AlternateContactNumber as AlternateMobileNo
    FROM Users
    WHERE UserId = @UserId
      AND IsDeleted = 0;
END
GO
PRINT N'Creating Procedure [dbo].[SP_User_GetOrCreateByMobile]...';


GO
CREATE PROCEDURE [dbo].[SP_User_GetOrCreateByMobile]
(
    @MobileNo DECIMAL(18,0),
    @EmailId NVARCHAR(200) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @UserId BIGINT;

    SELECT @UserId = UserId
    FROM Users
    WHERE MobileNo = @MobileNo;

    IF @UserId IS NULL
    BEGIN
        INSERT INTO Users
        (
            MobileNo, EmailId, IsActive, RoleId,
            CreatedOn, UpdatedOn
        )
        VALUES
        (
            @MobileNo, @EmailId, 1, 2,
            GETDATE(), GETDATE()
        );

        SET @UserId = SCOPE_IDENTITY();
    END

   SELECT UserId,RoleId,FirstName,MiddleName,LastName,EmailId as [Email],MobileNo as [Mobile] from Users WHERE UserId = @UserId ;

END
GO
PRINT N'Creating Procedure [dbo].[SP_User_UpdateProfile]...';


GO
CREATE   PROCEDURE [dbo].[SP_User_UpdateProfile]
(
    @UserId     BIGINT,
    @FirstName  NVARCHAR(100),
    @LastName   NVARCHAR(100),
    @EmailId    NVARCHAR(150),
  --  @MobileNo   NVARCHAR(15),
	@AlternateContactNumber NVARCHAR(15)
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRAN;

        -- 1️⃣ Validate user
        IF NOT EXISTS (SELECT 1 FROM Users WHERE UserId = @UserId)
        BEGIN
            RAISERROR ('User not found', 16, 1);
            ROLLBACK TRAN;
            RETURN;
        END

       -- Normalize first (enterprise style)
SET @EmailId = NULLIF(LTRIM(RTRIM(@EmailId)), '');
--SET @MobileNo = NULLIF(LTRIM(RTRIM(@MobileNo)), '');

-------------------------------------------------
-- Email Validation (Only if value exists)
-------------------------------------------------
IF @EmailId IS NOT NULL
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM Users 
        WHERE LTRIM(RTRIM(EmailId)) = @EmailId
          AND UserId <> @UserId
    )
    BEGIN
        RAISERROR ('Email already in use', 16, 1);
        ROLLBACK TRAN;
        RETURN;
    END
END

-------------------------------------------------
-- Mobile Validation (Only if value exists)
-------------------------------------------------
--IF @MobileNo IS NOT NULL
--BEGIN
--    IF EXISTS (
--        SELECT 1 
--        FROM Users 
--        WHERE MobileNo = @MobileNo
--          AND UserId <> @UserId
--    )
--    BEGIN
--        RAISERROR ('Mobile number already in use', 16, 1);
--        ROLLBACK TRAN;
--        RETURN;
--    END
--END

        -- 3️⃣ Update
       UPDATE Users
SET
    FirstName = CASE 
                    WHEN @FirstName IS NOT NULL 
                         AND LTRIM(RTRIM(@FirstName)) <> '' 
                         AND @FirstName <> FirstName
                    THEN @FirstName 
                    ELSE FirstName 
                END,

    LastName = CASE 
                    WHEN @LastName IS NOT NULL 
                         AND LTRIM(RTRIM(@LastName)) <> '' 
                         AND @LastName <> LastName
                    THEN @LastName 
                    ELSE LastName 
               END,

    EmailId = CASE 
                    WHEN @EmailId IS NOT NULL 
                         AND LTRIM(RTRIM(@EmailId)) <> '' 
                         AND @EmailId <> EmailId
                    THEN @EmailId 
                    ELSE EmailId 
              END,

    --MobileNo = CASE 
    --                WHEN @MobileNo IS NOT NULL 
    --                     AND LTRIM(RTRIM(@MobileNo)) <> '' 
    --                     AND @MobileNo <> MobileNo
    --                THEN @MobileNo 
    --                ELSE MobileNo 
    --           END,

    AlternateContactNumber = CASE 
                    WHEN @AlternateContactNumber IS NOT NULL 
                         AND LTRIM(RTRIM(@AlternateContactNumber)) <> '' 
                         AND @AlternateContactNumber <> AlternateContactNumber
                    THEN @AlternateContactNumber 
                    ELSE AlternateContactNumber 
               END,

    UpdatedOn = SYSDATETIME()
WHERE UserId = @UserId;

        COMMIT TRAN;

        SELECT 1 AS Success;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRAN;

        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[SP_UserAddress_Add]...';


GO
CREATE   PROCEDURE dbo.SP_UserAddress_Add
(
    @UserId BIGINT,
    @AddressTypeId INT,
    @CountryId INT,
    @StateId INT,
    @StateName VARCHAR(50),
    @City VARCHAR(100),
    @StreetAddress1 VARCHAR(100),
    @StreetAddress2 VARCHAR(100),
    @LandMark VARCHAR(510),
    @PinCode VARCHAR(10)
)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.UserAddresses
    (
        UserId,
        AddressTypeId,
        CountryId,
        StateId,
        StateName,
        City,
        StreetAddress1,
        StreetAddress2,
        LandMark,
        PinCode,
        IsActive,
        IsDeleted,
        CreatedOn,
        UpdatedOn
    )
    VALUES
    (
        @UserId,
        @AddressTypeId,
        @CountryId,
        @StateId,
        @StateName,
        @City,
        @StreetAddress1,
        @StreetAddress2,
        @LandMark,
        @PinCode,
        1,
        0,
        SYSUTCDATETIME(),
        SYSUTCDATETIME()
    );

    SELECT SCOPE_IDENTITY() AS AddressId;
END;
GO
PRINT N'Creating Procedure [dbo].[SP_UserAddress_Delete]...';


GO
CREATE   PROCEDURE dbo.SP_UserAddress_Delete
(
    @UserAddressId BIGINT,
    @UserId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE dbo.UserAddresses
    SET
        IsDeleted = 1,
        IsActive = 0,
        UpdatedOn = SYSUTCDATETIME()
    WHERE UserAddressId = @UserAddressId
      AND UserId = @UserId;
END;
GO
PRINT N'Creating Procedure [dbo].[SP_UserAddress_GetByUser]...';


GO
CREATE PROCEDURE [dbo].[SP_UserAddress_GetByUser]
(
    @UserId BIGINT,
    @UserAddressId BIGINT = NULL   -- optional parameter
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        UserAddressId,
        AddressTypeId,
        CountryId,
        StateId,
        StateName,
        City,
        StreetAddress1,
        StreetAddress2,
        LandMark,
        PinCode,
        IsActive,
        CreatedOn,
        UpdatedOn
    FROM dbo.UserAddresses
    WHERE UserId = @UserId
      AND IsDeleted = 0
      AND IsActive = 1
      AND (
            @UserAddressId IS NULL 
            OR UserAddressId = @UserAddressId
          )
    ORDER BY CreatedOn DESC;
END;
GO
PRINT N'Creating Procedure [dbo].[SP_UserAddress_Update]...';


GO
CREATE   PROCEDURE [dbo].[SP_UserAddress_Update]
(
    @UserAddressId BIGINT,
    @UserId BIGINT,
    @AddressTypeId INT,
    @CountryId INT,
    @StateId INT,
    @StateName VARCHAR(50),
    @City VARCHAR(100),
    @StreetAddress1 VARCHAR(100),
    @StreetAddress2 VARCHAR(100),
    @LandMark VARCHAR(510),
    @PinCode VARCHAR(10)
)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE dbo.UserAddresses
    SET
        AddressTypeId = @AddressTypeId,
        CountryId = @CountryId,
        StateId = @StateId,
        StateName = @StateName,
        City = @City,
        StreetAddress1 = @StreetAddress1,
        StreetAddress2 = @StreetAddress2,
        LandMark = @LandMark,
        PinCode = @PinCode,
        UpdatedOn = SYSUTCDATETIME()
    WHERE UserAddressId = @UserAddressId
      AND UserId = @UserId
      AND IsDeleted = 0
      AND IsActive = 1;
END;
GO
PRINT N'Creating Procedure [dbo].[SP_UserOrderDetails]...';


GO
CREATE PROCEDURE [dbo].[SP_UserOrderDetails]
(
    @PaymentTransactionId BIGINT,
    @UserId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    /* ----------------------------------------------------
       1️⃣ ORDER SUMMARY (GST + DISCOUNT + SHIPPING)
    ---------------------------------------------------- */

    SELECT
        PT.PaymentTransactionId AS OrderId,
        PT.CreatedOn            AS OrderDate,
        PT.PaymentMode,
        PT.TxnStatus,

        --------------------------------------------------
        -- AMOUNTS
        --------------------------------------------------
        ISNULL(PT.TxnAmount, 0)        AS TxnAmount,
        ISNULL(PT.ShippingCharges, 0)  AS ShippingCharges,

        --------------------------------------------------
        -- GST (FROM ITEM SNAPSHOT)
        --------------------------------------------------
        ISNULL(GSTAgg.CGST, 0) AS CGST,
        ISNULL(GSTAgg.SGST, 0) AS SGST,
        ISNULL(GSTAgg.IGST, 0) AS IGST,
        ISNULL(GSTAgg.GST, 0)  AS GST,

        --------------------------------------------------
        -- DISCOUNTS
        --------------------------------------------------
        ISNULL(PDAgg.ProductDiscount, 0)        AS ProductDiscount,
        ISNULL(PT.Promo_Code_Amount, 0)         AS CouponDiscount,
        ISNULL(PDAgg.ProductDiscount, 0) 
        + ISNULL(PT.Promo_Code_Amount, 0)       AS TotalDiscount,

        --------------------------------------------------
        -- GRAND TOTAL
        --------------------------------------------------
        ISNULL(PT.TxnAmount, 0) 
        + ISNULL(PT.ShippingCharges, 0)         AS GrandTotal

    FROM PaymentTransactions PT

    --------------------------------------------------
    -- GST AGGREGATION
    --------------------------------------------------
    OUTER APPLY
    (
        SELECT
            SUM(ISNULL(UPT.CGST,0)) AS CGST,
            SUM(ISNULL(UPT.SGST,0)) AS SGST,
            SUM(ISNULL(UPT.IGST,0)) AS IGST,
            SUM(ISNULL(UPT.GST_Amount,0)) AS GST
        FROM UserProductTransactions UPT
        WHERE UPT.PaymentTransactionId = PT.PaymentTransactionId
          AND UPT.IsDeleted = 0
    ) GSTAgg

    --------------------------------------------------
    -- PRODUCT DISCOUNT AGGREGATION
    --------------------------------------------------
    OUTER APPLY
    (
        SELECT
            SUM(ISNULL(UPT.ProductDiscountCost,0) * UPT.Quantity) AS ProductDiscount
        FROM UserProductTransactions UPT
        WHERE UPT.PaymentTransactionId = PT.PaymentTransactionId
          AND UPT.IsDeleted = 0
    ) PDAgg

    WHERE PT.PaymentTransactionId = @PaymentTransactionId
      AND PT.UserId = @UserId;


    /* ----------------------------------------------------
       2️⃣ SHIPPING ADDRESS
    ---------------------------------------------------- */

    SELECT TOP 1
        UA.UserAddressId AS ShippingAddressId,
        UA.StreetAddress1,
        UA.StreetAddress2,
        UA.LandMark,
        UA.City,
        UA.StateName,
        UA.CountryId,
        UA.PinCode
    FROM UserProductTransactions UPT
    INNER JOIN UserAddresses UA
        ON UA.UserAddressId = UPT.ShippingAddressId
    WHERE UPT.PaymentTransactionId = @PaymentTransactionId;


    /* ----------------------------------------------------
       3️⃣ ORDER ITEMS (FULL BREAKDOWN)
    ---------------------------------------------------- */

    SELECT
        P.ProductId,
        P.ProductName,
        P.ProductImgUrl,

        --------------------------------------------------
        -- QUANTITY
        --------------------------------------------------
        UPT.Quantity,

        --------------------------------------------------
        -- PRICING
        --------------------------------------------------
        UPT.ProductOriginalCost AS OriginalPrice,
        UPT.ProductCost         AS Price,

        --------------------------------------------------
        -- PRODUCT DISCOUNT
        --------------------------------------------------
        ISNULL(UPT.ProductDiscountCost,0) AS DiscountPerUnit,
        ISNULL(UPT.ProductDiscountCost,0) * UPT.Quantity AS TotalDiscount,

        --------------------------------------------------
        -- GST (FROM SNAPSHOT)
        --------------------------------------------------
        UPT.GST_Amount AS GST,
        UPT.CGST,
        UPT.SGST,
        UPT.IGST,

        --------------------------------------------------
        -- FINAL LINE TOTAL (AFTER DISCOUNT, GST INCLUDED)
        --------------------------------------------------
        (UPT.ProductCost * UPT.Quantity) AS Total,

        UPT.ExpectedDeliveryDate

    FROM UserProductTransactions UPT

    INNER JOIN Products P
        ON P.ProductId = UPT.ProductId

    WHERE UPT.PaymentTransactionId = @PaymentTransactionId
      AND UPT.IsDeleted = 0;

END
GO
PRINT N'Creating Procedure [dbo].[SP_UserOrders]...';


GO
CREATE PROCEDURE [dbo].[SP_UserOrders]
(
    @UserId INT
)
AS
BEGIN
    SET NOCOUNT ON;

SELECT 
PT.PaymentTransactionId AS OrderId,
p.ProductId,
P.ProductName,
PT.TxnStatus,
PT.TxnAMount,
PT.PaymentMode,
PT.OrderCurrentStatus
 from PaymentTransactions PT 
JOIN UserProductTransactions UPT ON PT.PaymentTransactionId = UPT.PaymentTransactionId
JOIN Products P on UPT.ProductId = P.ProductId
Where PT.UserId = @UserId

END
GO
PRINT N'Creating Procedure [dbo].[SP_UserOtp_Create]...';


GO
CREATE PROCEDURE SP_UserOtp_Create
(
    @UserId BIGINT,
    @OtpHash VARCHAR(256),
    @ExpiresAt DATETIME
)
AS
BEGIN
    INSERT INTO UserOtp (UserId, OtpHash, ExpiresAt)
    VALUES (@UserId, @OtpHash, @ExpiresAt);
END
GO
PRINT N'Creating Procedure [dbo].[SP_UserOtp_Save]...';


GO
CREATE   PROCEDURE [dbo].[SP_UserOtp_Save]
(
    @UserId     BIGINT,
    @OtpCode    VARCHAR(6),
    @ExpiryMin  INT = 5
)
AS
BEGIN
    SET NOCOUNT ON;

    -- Invalidate previous OTPs
    UPDATE UserOtp
    SET IsUsed = 1
    WHERE UserId = @UserId
      AND IsUsed = 0;

    INSERT INTO UserOtp
    (
        UserId,
        OtpHash,
        ExpiresAt,
        IsUsed
    )
    VALUES
    (
        @UserId,
        @OtpCode,
        DATEADD(MINUTE, @ExpiryMin, SYSUTCDATETIME()),
        0
    );
END;
GO
PRINT N'Creating Procedure [dbo].[SP_UserOtp_Validate]...';


GO
CREATE PROCEDURE [dbo].[SP_UserOtp_Validate]
(
    @Mobile   VARCHAR(15),
    @OtpCode  VARCHAR(6)
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @UserId BIGINT = 0;

    /*
      Step 1: Resolve UserId from Mobile
      (Assumes MobileNo is stored as VARCHAR / numeric safely)
    */
    SELECT TOP 1
        @UserId = U.UserId
    FROM [dbo].[Users] U
    WHERE CONVERT(VARCHAR(15), U.MobileNo) = @Mobile
      AND U.IsActive = 1
      AND U.IsDeleted = 0;

    -- If user not found → invalid
    IF (@UserId = 0)
    BEGIN
        SELECT 0 AS UserId;
        RETURN;
    END

    /*
      Step 2: Validate OTP for this UserId
    */
    IF EXISTS
    (
        SELECT 1
        FROM [dbo].[UserOtp]
        WHERE UserId = @UserId
          AND OtpHash = @OtpCode
          AND IsUsed = 0
          AND ExpiresAt >= SYSUTCDATETIME()
    )
    BEGIN
        /*
          Step 3: Mark OTP as used (single-use)
        */
        UPDATE [dbo].[UserOtp]
        SET
            IsUsed = 1,
            ExpiresAt = SYSUTCDATETIME()
        WHERE UserId = @UserId
          AND OtpHash = @OtpCode
          AND IsUsed = 0;

        /*
          Step 4: Return UserId (SUCCESS)
        */
        SELECT @UserId AS UserId;
    END
    ELSE
    BEGIN
        /*
          Invalid / expired OTP
        */
        SELECT 0 AS UserId;
    END
END;
GO
PRINT N'Creating Procedure [dbo].[SP_Cart_ApplyCoupon]...';


GO
CREATE PROCEDURE [dbo].[SP_Cart_ApplyCoupon]
(
    @CartId BIGINT,
    @UserId BIGINT = NULL,
    @CouponCode NVARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE 
        @CouponId BIGINT,
        @CartTotal DECIMAL(18,2),
        @DiscountAmount DECIMAL(18,2) = 0,
        @IsValid BIT,
        @Err NVARCHAR(200);

    --------------------------------------------------
    -- 1. Get CouponId
    --------------------------------------------------
    SELECT @CouponId = Coupon_Id
    FROM Tbl_Coupon_Info
    WHERE Coupon_Code = @CouponCode
      AND Status = 1;

    IF @CouponId IS NULL
    BEGIN
        RAISERROR('Invalid coupon code', 16, 1);
        RETURN;
    END

    --------------------------------------------------
    -- 2. Calculate Cart Total
    --------------------------------------------------
    SELECT @CartTotal = SUM(Quantity * UnitPrice)
    FROM CartItem
    WHERE CartId = @CartId;

    IF @CartTotal IS NULL SET @CartTotal = 0;

    --------------------------------------------------
    -- 3. Validate via Engine
    --------------------------------------------------
    EXEC dbo.SP_Coupon_ValidateAndApply
        @CouponId = @CouponId,
        @UserId = @UserId,
        @CartId = @CartId,
        @SubTotal = @CartTotal,
        @Recalculate = 1,
        @SyncCart = 0,
        @SyncCheckout = 0,
        @CheckoutTxnId = NULL,
        @IsValid = @IsValid OUTPUT,
        @CouponAmount = @DiscountAmount OUTPUT,
        @ErrorMessage = @Err OUTPUT;

    IF @IsValid = 0
    BEGIN
        RAISERROR(@Err, 16, 1);
        RETURN;
    END

    --------------------------------------------------
    -- 4. Apply Coupon to Cart
    --------------------------------------------------
    UPDATE Cart
    SET 
        Has_Promo_Code = 1,
        Promo_Code_ID = @CouponId,
        Promo_Code_Amount = @DiscountAmount,
        UpdatedOn = SYSDATETIME()
    WHERE CartId = @CartId;

    --------------------------------------------------
    -- 5. Return Result
    --------------------------------------------------
    SELECT 
        @CartTotal AS CartTotal,
        @DiscountAmount AS DiscountAmount,
        (@CartTotal - @DiscountAmount) AS FinalAmount;
END
GO
PRINT N'Creating Procedure [dbo].[SP_Checkout_ConfirmCOD]...';


GO
CREATE PROCEDURE [dbo].[SP_Checkout_ConfirmCOD]
(
    @UserId BIGINT,
    @CheckoutTransactionId BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRAN;

        DECLARE
            @CheckoutTxnId BIGINT,
            @FinalPaymentTxnId BIGINT,
            @CouponId BIGINT,
            @CouponAmount DECIMAL(18,2),
            @HasPromo BIT,
            @SubTotal DECIMAL(18,2),
            @ShippingCharges DECIMAL(18,2),
            @FinalAmount DECIMAL(18,2),
            @IsValid BIT,
            @Err NVARCHAR(200);

        --------------------------------------------------
        -- 1️⃣ Get Checkout
        --------------------------------------------------
        SELECT TOP 1
            @CheckoutTxnId = PaymentTransactionId,
            @CouponId = Promo_Code_ID,
            @CouponAmount = ISNULL(Promo_Code_Amount, 0),
            @HasPromo = ISNULL(Has_Promo_Code, 0),
            @ShippingCharges = ISNULL(ShippingCharges, 0)
        FROM CheckOutPaymentTransactions
        WHERE UserId = @UserId
          AND PaymentTransactionId = @CheckoutTransactionId
          AND OrderStatus = 'Open';

        IF @CheckoutTxnId IS NULL
        BEGIN
            RAISERROR ('No open checkout found for COD', 16, 1);
            ROLLBACK TRAN;
            RETURN;
        END

        --------------------------------------------------
        -- 2️⃣ Subtotal
        --------------------------------------------------
        SELECT 
            @SubTotal = SUM(ProductCost)
        FROM CheckOutUserProductTransactions
        WHERE PaymentTransactionId = @CheckoutTxnId;

        IF @SubTotal IS NULL SET @SubTotal = 0;

        --------------------------------------------------
        -- 3️⃣ Coupon Engine
        --------------------------------------------------
        IF @CouponId IS NOT NULL AND @HasPromo = 1
        BEGIN
            EXEC dbo.SP_Coupon_ValidateAndApply
                @CouponId,
                @UserId,
                NULL,
                @SubTotal,
                0,
                1,
                1,
                @CheckoutTxnId,
                @IsValid OUTPUT,
                @CouponAmount OUTPUT,
                @Err OUTPUT;

            IF @IsValid = 0
            BEGIN
                SET @CouponId = NULL;
                SET @CouponAmount = 0;
                SET @HasPromo = 0;
            END
        END

        --------------------------------------------------
        -- 4️⃣ Final Amount
        --------------------------------------------------
        SET @FinalAmount = @SubTotal + @ShippingCharges - @CouponAmount;
        IF @FinalAmount < 0 SET @FinalAmount = 0;

        --------------------------------------------------
        -- 5️⃣ Create Payment
        --------------------------------------------------
        INSERT INTO PaymentTransactions
        (
            UserId,
            PaymentMode,
            TxnStatus,
            PaymentStatus,
            CreatedOn,
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            TxnAmount,
            TxnMessage,
            Authorized,
            OrderCurrentStatus,
            ShippingCharges,
            Has_Promo_Code,
            Promo_Code_ID,
            Promo_Code_Amount
        )
        SELECT
            UserId,
            'Cash On Delivery',
            'SUCCESS',
            1,
            SYSDATETIME(),
            CurrencyCode,
            CurrencySymbol,
            CurrencyValue,
            @FinalAmount,
            'Transaction Successful through COD',
            1,
            6,
            @ShippingCharges,
            @HasPromo,
            @CouponId,
            CASE WHEN @HasPromo = 1 THEN @CouponAmount ELSE NULL END
        FROM CheckOutPaymentTransactions
        WHERE PaymentTransactionId = @CheckoutTxnId;

        SET @FinalPaymentTxnId = SCOPE_IDENTITY();

        --------------------------------------------------
        -- 6️⃣ Move Items (FIXED)
        --------------------------------------------------
        INSERT INTO UserProductTransactions
        (
            PaymentTransactionId,
            UserId,
            ProductId,
            SubProductId,
            Quantity,
			--------------------------------------------------
			-- PRICING SNAPSHOT (CRITICAL)
			--------------------------------------------------
			ProductOriginalCost,
			ProductCost,
			ProductDiscountPercentage,
			ProductDiscountCost,
			 --------------------------------------------------
			-- ADDRESS & META
			--------------------------------------------------
			ShippingAddressId,
			BillingAddressId,
			IsActive,
			IsDeleted,
			CreatedOn,
			UpdatedOn,
			CreatedBy,
			UpdatedBy,
			Status,

            CurrencyCode,
            CurrencyValue,
            CurrencySymbol,

            OrdersReturnReason,
            OrdersReturnAction,
            ReplacementTransactionId,
            IsReplaced,

            ExpectedDeliveryDate,
			--------------------------------------------------
			-- GST
			--------------------------------------------------
			GST_Percentage,
			GST_Amount,
			CGST,
			SGST,
			IGST,
			BaseAmount
        )
        SELECT
            @FinalPaymentTxnId,
            cup.UserId,
            cup.ProductId,
            cup.SubProductId,
            cup.Quantity,
			--------------------------------------------------
			-- ✅ PRICING (LOCKED FROM CHECKOUT)
			--------------------------------------------------
			p.ProductOriginalCost,
			cup.ProductCost,
			ISNULL(cup.ProductDiscountPercentage, 0),
			ISNULL(cup.ProductDiscountCost, 0),

			--------------------------------------------------
			-- META
			--------------------------------------------------
			cup.ShippingAddressId,
			cup.BillingAddressId,
			1,
			0,
			SYSDATETIME(),
			SYSDATETIME(),
			cup.CreatedBy,
			cup.UpdatedBy,
			0,

            chk.CurrencyCode,
            chk.CurrencyValue,
            chk.CurrencySymbol,

            cup.OrdersReturnReason,
            cup.OrdersReturnAction,
            cup.ReplacementTransactionId,
            cup.IsReplaced,
            cup.ExpectedDeliveryDate,

			--------------------------------------------------
			-- ✅ GST (via function)
			--------------------------------------------------
			p.GST,
			gst.GST_Amount,
			gst.CGST,
			gst.SGST,
			gst.IGST,
			gst.BaseAmount
		FROM CheckOutUserProductTransactions cup
		INNER JOIN CheckOutPaymentTransactions chk
			ON chk.PaymentTransactionId = cup.PaymentTransactionId
		INNER JOIN Products p
			ON p.ProductId = cup.ProductId
		INNER JOIN UserAddresses ua
			ON ua.UserAddressId = cup.ShippingAddressId
		CROSS APPLY dbo.fn_CalculateGST(
			cup.ProductCost,
			p.GST,
			ua.StateName
		) gst
		WHERE cup.PaymentTransactionId = @CheckoutTxnId;

        --------------------------------------------------
        -- 7️⃣ Close Checkout
        --------------------------------------------------
        UPDATE CheckOutPaymentTransactions
        SET OrderStatus = 'Closed',
            UpdatedOn = SYSDATETIME()
        WHERE PaymentTransactionId = @CheckoutTxnId;

        --------------------------------------------------
        -- 8️⃣ Clear Cart
        --------------------------------------------------
        DELETE CI
        FROM CartItem CI
        INNER JOIN Cart C ON CI.CartId = C.CartId
        WHERE C.UserId = @UserId;

        UPDATE Cart
        SET Status = 'CHECKED_OUT',
            UpdatedOn = SYSDATETIME()
        WHERE UserId = @UserId
          AND Status = 'ACTIVE';

        --------------------------------------------------
        -- 9️⃣ Attach Prescriptions
        --------------------------------------------------
        UPDATE Tbl_Presecription_Info
        SET Payment_Transaction_Id = @FinalPaymentTxnId
        WHERE User_Id = @UserId
          AND Payment_Transaction_Id IS NULL;

        COMMIT TRAN;

        SELECT @FinalPaymentTxnId AS PaymentTransactionId;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[SP_Checkout_UpsertAndCalculate]...';


GO
CREATE PROCEDURE [dbo].[SP_Checkout_UpsertAndCalculate]
(
    @UserId BIGINT,
    @PaymentMode NVARCHAR(50),
    @ShippingAddressId BIGINT,
    @BillingAddressId BIGINT,
    @ExpectedDeliveryDate DATETIME,
    @CurrencyCode NVARCHAR(10),
    @CurrencySymbol NVARCHAR(5),
    @CurrencyValue DECIMAL(18,6)
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRAN;

        --------------------------------------------------
        -- 0. Validation
        --------------------------------------------------
        IF @ShippingAddressId IS NULL OR @BillingAddressId IS NULL
        BEGIN
            RAISERROR ('Shipping and Billing Address are mandatory', 16, 1);
            ROLLBACK TRAN;
            RETURN;
        END

        DECLARE 
            @PaymentTransactionId BIGINT,
            @CartId BIGINT,
            @SubTotal DECIMAL(18,2) = 0,
            @ShippingCharges DECIMAL(18,2) = 0,
            @CouponId BIGINT = NULL,
            @CouponAmount DECIMAL(18,2) = 0,
            @HasPromo BIT = 0,
            @FinalAmount DECIMAL(18,2) = 0,
            @IsValid BIT,
            @Err NVARCHAR(200);

        --------------------------------------------------
        -- 1. Get Cart
        --------------------------------------------------
        SELECT TOP 1
            @CartId = CartId,
            @CouponId = Promo_Code_ID,
            @HasPromo = ISNULL(Has_Promo_Code, 0)
        FROM Cart
        WHERE UserId = @UserId
          AND Status = 'ACTIVE'
        ORDER BY CreatedOn DESC;

        IF @CartId IS NULL
        BEGIN
            RAISERROR ('No active cart found', 16, 1);
            ROLLBACK TRAN;
            RETURN;
        END

        --------------------------------------------------
        -- 2. Subtotal
        --------------------------------------------------
        SELECT @SubTotal = SUM(UnitPrice * Quantity)
        FROM CartItem
        WHERE CartId = @CartId;

        IF @SubTotal IS NULL OR @SubTotal = 0
        BEGIN
            RAISERROR ('Cart is empty', 16, 1);
            ROLLBACK TRAN;
            RETURN;
        END

        --------------------------------------------------
        -- 3. Coupon via Engine
        --------------------------------------------------
        IF @CouponId IS NOT NULL AND @HasPromo = 1
        BEGIN
            EXEC dbo.SP_Coupon_ValidateAndApply
                @CouponId = @CouponId,
                @UserId = @UserId,
                @CartId = @CartId,
                @SubTotal = @SubTotal,
                @Recalculate = 1,
                @SyncCart = 1,
                @SyncCheckout = 0,
                @CheckoutTxnId = NULL,
                @IsValid = @IsValid OUTPUT,
                @CouponAmount = @CouponAmount OUTPUT,
                @ErrorMessage = @Err OUTPUT;

            IF @IsValid = 0
            BEGIN
                SET @CouponId = NULL;
                SET @CouponAmount = 0;
                SET @HasPromo = 0;
            END
            ELSE
            BEGIN
                SET @HasPromo = CASE WHEN @CouponAmount > 0 THEN 1 ELSE 0 END;
            END
        END
        ELSE
        BEGIN
            SET @CouponId = NULL;
            SET @CouponAmount = 0;
            SET @HasPromo = 0;
        END

		 --------------------------------------------------
		-- 4. Discounted Amount (important step)
		--------------------------------------------------
		DECLARE @DiscountedAmount DECIMAL(18,2);

		SET @DiscountedAmount = @SubTotal - @CouponAmount;
		IF @DiscountedAmount < 0 SET @DiscountedAmount = 0;

		--------------------------------------------------
		-- 5. Shipping (based on discounted amount)
		--------------------------------------------------

		DECLARE @TotalWeightGrams DECIMAL(18,2);

		SELECT 
			@TotalWeightGrams = SUM(ISNULL(p.Weight,0) * ci.Quantity)
		FROM CartItem ci
		INNER JOIN Products p 
			ON ci.ProductId = p.ProductId
		WHERE ci.CartId = @CartId;

		IF @TotalWeightGrams IS NULL SET @TotalWeightGrams = 0;

		SET @ShippingCharges = dbo.fn_GetShippingCharge(
			@DiscountedAmount,
			@PaymentMode,
			@TotalWeightGrams
		);

		--------------------------------------------------
		-- 5.1. Final Amount
		--------------------------------------------------
		SET @FinalAmount = @DiscountedAmount + @ShippingCharges;

        --------------------------------------------------
        -- 6. Get/Create Checkout
        --------------------------------------------------
        SELECT TOP 1
            @PaymentTransactionId = PaymentTransactionId
        FROM CheckOutPaymentTransactions
        WHERE UserId = @UserId
          AND OrderStatus = 'Open'
        ORDER BY CreatedOn DESC;

        IF @PaymentTransactionId IS NULL
        BEGIN
            INSERT INTO CheckOutPaymentTransactions
            (
                UserId, CreatedOn, TxnStatus, PaymentStatus,
                OrderStatus, OrderCurrentStatus, PaymentMode,
                CurrencyCode, CurrencySymbol, CurrencyValue
            )
            VALUES
            (
                @UserId, SYSDATETIME(), 'Checkout', 0,
                'Open', 10, @PaymentMode,
                @CurrencyCode, @CurrencySymbol, @CurrencyValue
            );

            SET @PaymentTransactionId = SCOPE_IDENTITY();
        END

        --------------------------------------------------
        -- 7. Update Checkout
        --------------------------------------------------
        UPDATE CheckOutPaymentTransactions
        SET
            TxnAmount         = @FinalAmount,
            ShippingCharges   = @ShippingCharges,
            Has_Promo_Code    = @HasPromo,
            Promo_Code_ID     = @CouponId,
            Promo_Code_Amount = CASE WHEN @HasPromo = 1 THEN @CouponAmount ELSE NULL END,
            PaymentMode       = @PaymentMode,
            UpdatedOn         = SYSDATETIME()
        WHERE PaymentTransactionId = @PaymentTransactionId;

        --------------------------------------------------
        -- 8. Snapshot Items
        --------------------------------------------------
        DELETE FROM CheckOutUserProductTransactions
        WHERE PaymentTransactionId = @PaymentTransactionId;

        INSERT INTO CheckOutUserProductTransactions
        (
            PaymentTransactionId, UserId, ProductId, SubProductId,
            Quantity, ProductCost, ProductDiscountPercentage,
            ProductDiscountCost, ShippingAddressId, BillingAddressId,
            IsActive, IsDeleted, CreatedOn, UpdatedOn,
            CreatedBy, UpdatedBy, Status,
            CurrencyCode, CurrencyValue, CurrencySymbol,
            ExpectedDeliveryDate
        )
        SELECT
            @PaymentTransactionId,
            @UserId,
            ci.ProductId,
            NULL,
            ci.Quantity,
            ci.UnitPrice * ci.Quantity,
            ISNULL(p.ProductDiscountPercentage, 0),
            ISNULL(p.ProductDiscountCost, 0),
            @ShippingAddressId,
            @BillingAddressId,
            1, 0,
            SYSDATETIME(), SYSDATETIME(),
            @UserId, @UserId, 0,
            @CurrencyCode, @CurrencyValue, @CurrencySymbol,
            @ExpectedDeliveryDate
        FROM CartItem ci
        INNER JOIN Products p ON ci.ProductId = p.ProductId
        WHERE ci.CartId = @CartId;

        COMMIT TRAN;

        --------------------------------------------------
        -- 9. Return
        --------------------------------------------------
        SELECT 
            @PaymentTransactionId AS PaymentTransactionId,
            @SubTotal AS SubTotal,
            @CouponAmount AS Discount,
            @ShippingCharges AS ShippingCharges,
            @FinalAmount AS PayableAmount,
            @HasPromo AS HasPromo;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
        THROW;
    END CATCH
END
GO
PRINT N'Refreshing Procedure [dbo].[Sp_DispatchOrders]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Sp_DispatchOrders]';


GO
PRINT N'Refreshing Procedure [dbo].[Sp_DispatchOrdersNew]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Sp_DispatchOrdersNew]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_DownloadEcomExcel]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_DownloadEcomExcel]';


GO
PRINT N'Refreshing Procedure [Healthurwealth].[NotifyMe]...';


GO
EXECUTE sp_refreshsqlmodule N'[Healthurwealth].[NotifyMe]';


GO
PRINT N'Refreshing Procedure [dbo].[Sp_DispatchedReports]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Sp_DispatchedReports]';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Cart] WITH CHECK CHECK CONSTRAINT [FK_Cart_Coupon];

ALTER TABLE [dbo].[CartItem] WITH CHECK CHECK CONSTRAINT [FK_CartItem_Cart];

ALTER TABLE [dbo].[UserOtp] WITH CHECK CHECK CONSTRAINT [FK_UserOtp_User];

ALTER TABLE [dbo].[Cart] WITH CHECK CHECK CONSTRAINT [CK_Cart_Owner];


GO
PRINT N'Update complete.';


GO
